# Generated by Django 5.0.2 on 2024-03-05 08:03

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product.category",
            ),
        ),
    ]
